# ===============================
# = App Settings
# ===============================
app:
  message: Welcome to TMS (Training Management System) by ${app.organization}. You are currently using ${app.name} in QA environment.
  env: qa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tms_qa?useSSL=false
    username: root
    password: root